[versions]

android-gradle-plugin = "8.13.2"
android-application = "8.13.2"
kotlin-android = "2.3.10"


[libraries]

androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version = "1.13.0" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version = "1.7.1" }
material = { group = "com.google.android.material", name = "material", version = "1.13.0" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version = "2.2.1" }
androidx-navigation-fragment-ktx = { group = "androidx.navigation", name = "navigation-fragment-ktx", version = "2.9.7" }
androidx-navigation-ui-ktx = { group = "androidx.navigation", name = "navigation-ui-ktx", version = "2.9.7" }
junit = { group = "junit", name = "junit", version = "4.13.2" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version = "1.2.1" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version = "3.6.1" }
supabase-bom = { group = "io.github.jan-tennert.supabase", name = "bom", version = "3.3.0" }
supabase-gotrue = { group = "io.github.jan-tennert.supabase", name = "auth-kt" }
supabase-postgrest = { group = "io.github.jan-tennert.supabase", name = "postgrest-kt" }


[plugins]

android-application = { id = "com.android.application", version.ref = "android-application" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin-android" }
